(function(g){var window=this;'use strict';var TAv=function(p,C){p.Jk("onAutonavCoundownStarted",C)},MSE=function(p){var C,V,N;
return p==null?void 0:(C=p.playerOverlays)==null?void 0:(V=C.playerOverlayRenderer)==null?void 0:(N=V.autoplay)==null?void 0:N.playerOverlayAutoplayRenderer},H9=function(p,C,V){g.aL(p.element,"ytp-suggestion-set",!!C.videoId);
var N=C.playlistId;V=C.b8(V?V:"mqdefault.jpg");var H=null,X=null;C instanceof g.ls&&(C.lengthText?(H=C.lengthText||null,X=C.uN||null):C.lengthSeconds&&(H=g.u$(C.lengthSeconds),X=g.u$(C.lengthSeconds,!0)));var d=!!N;N=d&&g.aI(N).type==="RD";var a=C instanceof g.ls?C.isLivePlayback:null,E=C instanceof g.ls?C.isUpcoming:null,l=C.author,t=C.shortViewCount,c=C.publishedTimeText,T=[],M=[];l&&T.push(l);t&&(T.push(t),M.push(t));c&&M.push(c);V={title:C.title,author:l,author_and_views:T.join(" \u2022 "),aria_label:C.ariaLabel||
g.c8("Watch $TITLE",{TITLE:C.title}),duration:H,timestamp:X,url:C.uT(),is_live:a,is_upcoming:E,is_list:d,is_mix:N,background:V?"background-image: url("+V+")":"",views_and_publish_time:M.join(" \u2022 "),autoplayAlternativeHeader:C.TY};C instanceof g.Ej&&(V.playlist_length=C.playlistLength);p.update(V)},Xb=function(p){var C=p.K(),V=C.S;
g.w.call(this,{L:"a",B:"ytp-autonav-suggestion-card",X:{href:"{{url}}",target:V?C.Z:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},j:[{L:"div",i_:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],X:{style:"{{background}}"},j:[{L:"div",X:{"aria-label":"{{timestamp}}"},i_:["ytp-autonav-timestamp"],Ak:"{{duration}}"},{L:"div",i_:["ytp-autonav-live-stamp"],Ak:"Live"},{L:"div",
i_:["ytp-autonav-upcoming-stamp"],Ak:"Upcoming"},{L:"div",B:"ytp-autonav-list-overlay",j:[{L:"div",B:"ytp-autonav-mix-text",Ak:"Mix"},{L:"div",B:"ytp-autonav-mix-icon"}]}]},{L:"div",i_:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],Ak:"{{title}}"},{L:"div",i_:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],Ak:"{{author}}"},{L:"div",i_:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],Ak:"{{views_and_publish_time}}"}]});this.N=p;this.suggestion=
null;this.T=V;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},dp=function(p,C){C=C===void 0?!1:C;
g.w.call(this,{L:"div",B:"ytp-autonav-endscreen-countdown-overlay"});var V=this;this.D=C;this.cancelCommand=this.W=void 0;this.V=0;this.container=new g.w({L:"div",B:"ytp-autonav-endscreen-countdown-container"});g.R(this,this.container);this.container.u_(this.element);C=p.K();var N=C.S;this.N=p;this.suggestion=null;this.onVideoDataChange("newdata",this.N.getVideoData());this.U(p,"videodatachange",this.onVideoDataChange);this.T=new g.w({L:"div",B:"ytp-autonav-endscreen-upnext-container",X:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},j:[{L:"div",B:"ytp-autonav-endscreen-upnext-header"},{L:"div",B:"ytp-autonav-endscreen-upnext-alternative-header",Ak:"{{autoplayAlternativeHeader}}"},{L:"a",B:"ytp-autonav-endscreen-link-container",X:{href:"{{url}}",target:N?C.Z:""},j:[{L:"div",B:"ytp-autonav-endscreen-upnext-thumbnail",X:{style:"{{background}}"},j:[{L:"div",X:{"aria-label":"{{timestamp}}"},i_:["ytp-autonav-timestamp"],
Ak:"{{duration}}"},{L:"div",i_:["ytp-autonav-live-stamp"],Ak:"Live"},{L:"div",i_:["ytp-autonav-upcoming-stamp"],Ak:"Upcoming"}]},{L:"div",B:"ytp-autonav-endscreen-video-info",j:[{L:"div",B:"ytp-autonav-endscreen-premium-badge"},{L:"div",B:"ytp-autonav-endscreen-upnext-title",Ak:"{{title}}"},{L:"div",B:"ytp-autonav-endscreen-upnext-author",Ak:"{{author}}"},{L:"div",B:"ytp-autonav-view-and-date",Ak:"{{views_and_publish_time}}"},{L:"div",B:"ytp-autonav-author-and-view",Ak:"{{author_and_views}}"}]}]}]});
g.R(this,this.T);this.T.u_(this.container.element);N||this.U(this.T.rV("ytp-autonav-endscreen-link-container"),"click",this.X8);this.N.createClientVe(this.container.element,this,115127);this.N.createClientVe(this.T.rV("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.w({L:"div",B:"ytp-autonav-overlay"});g.R(this,this.overlay);this.overlay.u_(this.container.element);this.C=new g.w({L:"div",B:"ytp-autonav-endscreen-button-container"});g.R(this,this.C);this.C.u_(this.container.element);
this.cancelButton=new g.w({L:"button",i_:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",C.G("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{"aria-label":"Cancel autoplay"},Ak:"Cancel"});g.R(this,this.cancelButton);this.cancelButton.u_(this.C.element);this.cancelButton.listen("click",this.Ew,this);this.N.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.w({L:"a",i_:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
C.G("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{href:"{{url}}",role:"button","aria-label":"Play next video"},Ak:"Play Now"});g.R(this,this.playButton);this.playButton.u_(this.C.element);this.playButton.listen("click",this.X8,this);this.N.createServerVe(this.playButton.element,this.playButton,!0);(C=this.N.getVideoData())&&J88(this,C);this.S=new g.Go(function(){m7F(V)},500);
g.R(this,this.S);this.j0();this.U(p,"autonavvisibility",this.j0);this.N.G("web_autonav_color_transition")&&(this.U(p,"autonavchange",this.SC),this.U(p,"onAutonavCoundownStarted",this.WMr))},iA=function(p){var C=p.N.v_(!0,p.N.isFullscreen());
g.aL(p.container.element,"ytp-autonav-endscreen-small-mode",p.Qf(C));g.aL(p.container.element,"ytp-autonav-endscreen-is-premium",!!p.suggestion&&!!p.suggestion.LSe);g.aL(p.N.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!p.N.lW());g.aL(p.N.getRootNode(),"countdown-running",p.WI());g.aL(p.container.element,"ytp-player-content",p.N.lW());g.MK(p.overlay.element,{width:C.width+"px"});if(!p.WI()){p.N.lW()?v7y(p,Math.round(FoP(p)/1E3)):v7y(p);C=!!p.suggestion&&!!p.suggestion.TY;var V=p.N.lW()||
!C;g.aL(p.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!V&&C);g.aL(p.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",V&&!C);p.C.F0(p.N.lW());g.aL(p.element,"ytp-enable-w2w-color-transitions",S8c(p))}},m7F=function(p){var C=FoP(p),V=Math,N=V.min;
var H=p.V?Date.now()-p.V:0;V=N.call(V,H,C);v7y(p,Math.ceil((C-V)/1E3));C-V<=500&&p.WI()?p.select(!0):p.WI()&&p.S.start()},FoP=function(p){if(p.N.isFullscreen()){var C;
p=(C=p.N.getVideoData())==null?void 0:C.qY;return p===-1||p===void 0?8E3:p}return p.N.hx()>=0?p.N.hx():g.a3(p.N.K().experiments,"autoplay_time")||1E4},J88=function(p,C){C=C.getWatchNextResponse();
var V,N;C=(V=MSE(C))==null?void 0:(N=V.nextButton)==null?void 0:N.buttonRenderer;p.W=C==null?void 0:C.navigationEndpoint;V=C==null?void 0:C.trackingParams;p.playButton&&V&&p.N.setTrackingParams(p.playButton.element,V)},S8c=function(p){var C;
return!((C=p.N.getVideoData())==null||!C.watchToWatchTransitionRenderer)},v7y=function(p,C){C=C===void 0?-1:C;
p=p.T.rV("ytp-autonav-endscreen-upnext-header");g.He(p);if(C>=0){C=String(C);var V="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],N="Up next in $SECONDS".indexOf(V);if(N>=0){p.appendChild(g.Vf("Up next in $SECONDS".slice(0,N)));var H=g.ju("span");g.HF(H,"ytp-autonav-endscreen-upnext-header-countdown-number");g.h2(H,C);p.appendChild(H);p.appendChild(g.Vf("Up next in $SECONDS".slice(N+V.length)));return}}g.h2(p,"Up next")},hi=function(p,C){g.w.call(this,{L:"div",
i_:["html5-endscreen","ytp-player-content",C||"base-endscreen"]});this.created=!1;this.player=p},sP=function(p){g.w.call(this,{L:"div",
i_:["ytp-upnext","ytp-player-content"],X:{"aria-label":"{{aria_label}}"},j:[{L:"div",B:"ytp-cued-thumbnail-overlay-image",X:{style:"{{background}}"}},{L:"span",B:"ytp-upnext-top",j:[{L:"span",B:"ytp-upnext-header",Ak:"Up Next"},{L:"span",B:"ytp-upnext-title",Ak:"{{title}}"},{L:"span",B:"ytp-upnext-author",Ak:"{{author}}"}]},{L:"a",B:"ytp-upnext-autoplay-icon",X:{role:"button",href:"{{url}}","aria-label":"Play next video"},j:[{L:"svg",X:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
j:[{L:"circle",B:"ytp-svg-autoplay-circle",X:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{L:"circle",B:"ytp-svg-autoplay-ring",X:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{L:"path",B:"ytp-svg-fill",X:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{L:"span",B:"ytp-upnext-bottom",j:[{L:"span",B:"ytp-upnext-cancel"},{L:"span",B:"ytp-upnext-paused",
Ak:"Autoplay is paused"}]}]});this.api=p;this.cancelButton=null;this.W=this.rV("ytp-svg-autoplay-ring");this.V=this.notification=this.T=this.suggestion=null;this.S=new g.Go(this.yD,5E3,this);this.C=0;var C=this.rV("ytp-upnext-cancel");this.cancelButton=new g.w({L:"button",i_:["ytp-upnext-cancel-button","ytp-button"],X:{tabindex:"0","aria-label":"Cancel autoplay"},Ak:"Cancel"});g.R(this,this.cancelButton);this.cancelButton.listen("click",this.uD,this);this.cancelButton.u_(C);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.R(this,this.S);this.api.createClientVe(this.element,this,18788);C=this.rV("ytp-upnext-autoplay-icon");this.U(C,"click",this.m4);this.api.createClientVe(C,this,115130);this.F8();this.U(p,"autonavvisibility",this.F8);this.U(p,"mdxnowautoplaying",this.Acr);this.U(p,"mdxautoplaycanceled",this.xZn);g.aL(this.element,"ytp-upnext-mobile",this.api.K().C)},Koy=function(p,C){if(C)return C;
if(p.api.isFullscreen()){var V;p=(V=p.api.getVideoData())==null?void 0:V.qY;return p===-1||p===void 0?8E3:p}return p.api.hx()>=0?p.api.hx():g.a3(p.api.K().experiments,"autoplay_time")||1E4},D7c=function(p,C){C=Koy(p,C);
var V=Math,N=V.min;var H=(0,g.U2)()-p.C;V=N.call(V,H,C);C=C===0?1:Math.min(V/C,1);p.W.setAttribute("stroke-dashoffset",""+-211*(C+1));C>=1&&p.WI()&&p.api.getPresentingPlayerType()!==3?p.select(!0):p.WI()&&p.T.start()},aU=function(p){hi.call(this,p,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.w({L:"div",B:"ytp-suggestion-panel",j:[{L:"div",i_:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],Ak:"More videos"}]});this.J=new g.w({L:"div",B:"ytp-suggestions-container"});this.videos=[];this.V=null;this.W=this.D=!1;this.C=new dp(this.player);g.R(this,this.C);this.C.u_(this.element);p.getVideoData().qg?this.T=this.C:(this.T=new sP(p),g.R$(this.player,this.T.element,4),g.R(this,this.T));this.overlay=new g.w({L:"div",
B:"ytp-autonav-overlay-cancelled-state"});g.R(this,this.overlay);this.overlay.u_(this.element);this.S=new g.Ir(this);g.R(this,this.S);g.R(this,this.table);this.table.u_(this.element);this.table.show();g.R(this,this.J);this.J.u_(this.table.element);this.hide()},EP=function(p){var C=p.lW();
C!==p.W&&(p.W=C,p.player.publish("autonavvisibility"),p.W?(p.C!==p.T&&p.C.hide(),p.table.hide()):(p.C!==p.T&&p.C.show(),p.table.show()))},lA=function(p,C){g.w.call(this,{L:"button",
i_:["ytp-watch-on-youtube-button","ytp-button"],Ak:"{{content}}"});this.N=p;this.buttonType=this.buttonType=C;this.yB();this.buttonType===2&&g.d0(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.yB);this.F0(!0)},ti=function(p,C){hi.call(this,p,"embeds-lite-endscreen");
this.N=p;this.T=C;this.N.createClientVe(this.element,this,156943);this.watchButton=new lA(p,2);g.R(this,this.watchButton);this.watchButton.u_(this.element);this.hide()},uup=function(p){hi.call(this,p,"subscribecard-endscreen");
this.T=new g.w({L:"div",B:"ytp-subscribe-card",j:[{L:"img",B:"ytp-author-image",X:{src:"{{profilePicture}}"}},{L:"div",B:"ytp-subscribe-card-right",j:[{L:"div",B:"ytp-author-name",Ak:"{{author}}"},{L:"div",B:"html5-subscribe-button-container"}]}]});g.R(this,this.T);this.T.u_(this.element);var C=p.getVideoData();this.subscribeButton=new g.ER("Subscribe",null,"Unsubscribe",null,!0,!1,C.wb,C.subscribed,"trailer-endscreen",null,p,!1);g.R(this,this.subscribeButton);this.subscribeButton.u_(this.T.rV("html5-subscribe-button-container"));
this.U(p,"videodatachange",this.Pr);this.Pr();this.hide()},c9=function(p){var C=p.K(),V=g.fR||g.cg?{style:"will-change: opacity"}:void 0,N=C.S,H=["ytp-videowall-still"];
C.C&&H.push("ytp-videowall-show-text");g.w.call(this,{L:"a",i_:H,X:{href:"{{url}}",target:N?C.Z:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},j:[{L:"div",B:"ytp-videowall-still-image",X:{style:"{{background}}"}},{L:"span",B:"ytp-videowall-still-info",X:{"aria-hidden":"true"},j:[{L:"span",B:"ytp-videowall-still-info-bg",j:[{L:"span",B:"ytp-videowall-still-info-content",X:V,j:[{L:"span",B:"ytp-videowall-still-info-title",Ak:"{{title}}"},
{L:"span",B:"ytp-videowall-still-info-author",Ak:"{{author_and_views}}"},{L:"span",B:"ytp-videowall-still-info-live",Ak:"Live"},{L:"span",B:"ytp-videowall-still-info-duration",Ak:"{{duration}}"}]}]}]},{L:"span",i_:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},j:[{L:"span",B:"ytp-videowall-still-listlabel-icon"},"Playlist",{L:"span",B:"ytp-videowall-still-listlabel-length",j:[" (",{L:"span",Ak:"{{playlist_length}}"},")"]}]},{L:"span",i_:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},j:[{L:"span",B:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{L:"span",B:"ytp-videowall-still-listlabel-length",Ak:" (50+)"}]}]});this.suggestion=null;this.C=N;this.api=p;this.T=new g.Ir(this);g.R(this,this.T);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.T.U(p,"videodatachange",this.onVideoDataChange);p.createServerVe(this.element,this);this.onVideoDataChange()},Ta=function(p){hi.call(this,p,"videowall-endscreen");
var C=this;this.N=p;this.V=0;this.stills=[];this.S=this.videoData=null;this.W=this.J=!1;this.Z=null;this.C=new g.Ir(this);g.R(this,this.C);this.D=new g.Go(function(){g.d0(C.element,"ytp-show-tiles")},0);
g.R(this,this.D);var V=new g.w({L:"button",i_:["ytp-button","ytp-endscreen-previous"],X:{"aria-label":"Previous"},j:[g.mz()]});g.R(this,V);V.u_(this.element);V.listen("click",this.fb,this);this.table=new g.sy({L:"div",B:"ytp-endscreen-content"});g.R(this,this.table);this.table.u_(this.element);V=new g.w({L:"button",i_:["ytp-button","ytp-endscreen-next"],X:{"aria-label":"Next"},j:[g.va()]});g.R(this,V);V.u_(this.element);V.listen("click",this.iD,this);p.getVideoData().qg?this.T=new dp(p,!0):this.T=
new sP(p);g.R(this,this.T);g.R$(this.player,this.T.element,4);p.createClientVe(this.element,this,158789);this.hide()},M0=function(p){return g.nT(p.player)&&p.RF()&&!p.S},Ji=function(p){var C=p.lW();
C!==p.J&&(p.J=C,p.player.publish("autonavvisibility"))},m7=function(p){hi.call(this,p,"watch-again-on-youtube-endscreen");
this.watchButton=new lA(p,1);g.R(this,this.watchButton);this.watchButton.u_(this.element);g.cve(p)&&(this.T=new g.GS(p),g.R(this,this.T),this.C=new g.w({L:"div",i_:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],X:{tabIndex:"-1"},j:[this.T]}),g.R(this,this.C),this.T.u_(this.C.element),this.C.u_(this.element));p.createClientVe(this.element,this,156914);this.hide()},OJ2=function(p){g.IT.call(this,p);
var C=this;this.endScreen=null;this.C=this.T=this.V=this.S=!1;this.listeners=new g.Ir(this);g.R(this,this.listeners);var V=p.K(),N=p.getVideoData();N=N&&N.limitedPlaybackDurationInSeconds!==0;g.sB(g.ZW(V))&&N&&!g.kj(p)?(this.C=!0,this.endScreen=new ti(p,g.FE(p))):p.isEmbedsShortsMode()?this.endScreen=new m7(p):ZJc(p)?(this.S=!0,U7r(this),this.T?this.endScreen=new aU(p):this.endScreen=new Ta(p)):V.Mn?this.endScreen=new uup(p):this.endScreen=new hi(p);g.R(this,this.endScreen);g.R$(p,this.endScreen.element,
4);fC1(this);this.listeners.U(p,"videodatachange",this.onVideoDataChange,this);this.listeners.U(p,g.No("endscreen"),function(H){C.onCueRangeEnter(H)});
this.listeners.U(p,g.H8("endscreen"),function(H){C.onCueRangeExit(H)})},U7r=function(p){var C=p.player.getVideoData();
if(!C||p.T===C.Fx&&p.V===C.qg)return!1;p.T=C.Fx;p.V=C.qg;return!0},ZJc=function(p){p=p.K();
return p.QZ&&!p.Mn},fC1=function(p){p.player.p7("endscreen");
var C=p.player.getVideoData();C=new g.jY(Math.max((C.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var V=new g.jY(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});p.player.d7([C,V])};
g.I$.prototype.hx=g.Ns(14,function(){return this.app.hx()});
g.SM.prototype.hx=g.Ns(13,function(){return this.getVideoData().eG});
g.fT.prototype.Gf=g.Ns(12,function(p){this.SU().Gf(p)});
g.fZ.prototype.Gf=g.Ns(11,function(p){this.T!==p&&(this.T=p,this.Pr())});
g.ov.prototype.Gf=g.Ns(10,function(p){this.overflowButton&&this.overflowButton.Gf(p)});
g.fT.prototype.h2=g.Ns(9,function(p){this.SU().h2(p)});
g.bW.prototype.h2=g.Ns(8,function(p){this.C!==p&&(this.C=p,this.Pr())});
g.ov.prototype.h2=g.Ns(7,function(p){this.shareButton&&this.shareButton.h2(p)});
g.fT.prototype.fn=g.Ns(6,function(p){this.SU().fn(p)});
g.Hz.prototype.fn=g.Ns(5,function(p){this.Si!==p&&(this.Si=p,this.ZI())});
g.fT.prototype.iQ=g.Ns(4,function(p){this.SU().iQ(p)});
g.ov.prototype.iQ=g.Ns(3,function(p){this.Vh!==p&&(this.Vh=p,this.Mr())});g.v(Xb,g.w);Xb.prototype.select=function(){this.N.uy(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Ve||void 0)&&this.N.logClick(this.element)};
Xb.prototype.onClick=function(p){g.EO(p,this.N,this.T,this.suggestion.sessionData||void 0)&&this.select()};
Xb.prototype.onKeyPress=function(p){switch(p.keyCode){case 13:case 32:p.defaultPrevented||(this.select(),p.preventDefault())}};g.v(dp,g.w);g.h=dp.prototype;g.h.y_=function(p){this.suggestion!==p&&(this.suggestion=p,H9(this.T,p),this.playButton.updateValue("url",this.suggestion.uT()),iA(this))};
g.h.WI=function(){return this.V>0};
g.h.pn=function(){this.WI()||(this.V=Date.now(),m7F(this),TAv(this.N,FoP(this)),g.aL(this.N.getRootNode(),"countdown-running",this.WI()))};
g.h.qA=function(){this.QP();m7F(this);var p=this.T.rV("ytp-autonav-endscreen-upnext-header");p&&g.h2(p,"Up next")};
g.h.QP=function(){this.WI()&&(this.S.stop(),this.V=0)};
g.h.select=function(p){this.N.nextVideo(!1,p===void 0?!1:p);this.QP()};
g.h.X8=function(p){g.EO(p,this.N)&&(p.currentTarget===this.playButton.element?this.N.logClick(this.playButton.element):p.currentTarget===this.T.rV("ytp-autonav-endscreen-link-container")&&(p=this.T.rV("ytp-autonav-endscreen-link-container"),this.N.logVisibility(p,!0),this.N.logClick(p)),this.W?(this.N.Jk("innertubeCommand",this.W),this.QP()):this.select())};
g.h.Ew=function(){this.N.logClick(this.cancelButton.element);g.A_(this.N,!0);this.cancelCommand&&this.N.Jk("innertubeCommand",this.cancelCommand)};
g.h.onVideoDataChange=function(p,C){J88(this,C);p=C.getWatchNextResponse();var V,N;p=(V=MSE(p))==null?void 0:(N=V.cancelButton)==null?void 0:N.buttonRenderer;this.cancelCommand=p==null?void 0:p.command};
g.h.WMr=function(p){if(S8c(this)){var C=this.N.getVideoData().watchToWatchTransitionRenderer,V=C==null?void 0:C.fromColorPaletteDark;C=C==null?void 0:C.toColorPaletteDark;if(V&&C){var N=this.element;N.style.setProperty("--w2w-start-background-color",g.R0(V.surgeColor));N.style.setProperty("--w2w-start-primary-text-color",g.R0(V.primaryTitleColor));N.style.setProperty("--w2w-start-secondary-text-color",g.R0(V.secondaryTitleColor));N.style.setProperty("--w2w-end-background-color",g.R0(C.surgeColor));
N.style.setProperty("--w2w-end-primary-text-color",g.R0(C.primaryTitleColor));N.style.setProperty("--w2w-end-secondary-text-color",g.R0(C.secondaryTitleColor));N.style.setProperty("--w2w-animation-duration",p+"ms")}g.aL(this.element,"ytp-w2w-animate",!0)}};
g.h.SC=function(p){this.N.G("web_autonav_color_transition")&&p!==2&&g.aL(this.element,"ytp-w2w-animate",!1)};
g.h.j0=function(){var p=this.N.lW();this.D&&this.n4!==p&&this.F0(p);iA(this);this.N.logVisibility(this.container.element,p);this.N.logVisibility(this.cancelButton.element,p);this.N.logVisibility(this.T.rV("ytp-autonav-endscreen-link-container"),p);this.N.logVisibility(this.playButton.element,p)};
g.h.Qf=function(p){return p.width<400||p.height<459};g.v(hi,g.w);g.h=hi.prototype;g.h.create=function(){this.created=!0};
g.h.destroy=function(){this.created=!1};
g.h.RF=function(){return!1};
g.h.lW=function(){return!1};
g.h.nL=function(){return!1};g.v(sP,g.w);g.h=sP.prototype;g.h.yD=function(){this.notification&&(this.S.stop(),this.rY(this.V),this.V=null,this.notification.close(),this.notification=null)};
g.h.y_=function(p){this.suggestion=p;H9(this,p,"hqdefault.jpg")};
g.h.F8=function(){this.F0(this.api.lW());this.api.logVisibility(this.element,this.api.lW());this.api.logVisibility(this.rV("ytp-upnext-autoplay-icon"),this.api.lW());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.lW())};
g.h.mZa=function(){window.focus();this.yD()};
g.h.pn=function(p){var C=this;this.WI()||(g.lV("a11y-announce","Up Next "+this.suggestion.title),this.C=(0,g.U2)(),this.T=new g.Go(function(){D7c(C,p)},25),D7c(this,p),TAv(this.api,Koy(this,p)));
g.hk(this.element,"ytp-upnext-autoplay-paused")};
g.h.hide=function(){g.w.prototype.hide.call(this)};
g.h.WI=function(){return!!this.T};
g.h.qA=function(){this.QP();this.C=(0,g.U2)();D7c(this);g.d0(this.element,"ytp-upnext-autoplay-paused")};
g.h.QP=function(){this.WI()&&(this.T.dispose(),this.T=null)};
g.h.select=function(p){p=p===void 0?!1:p;if(this.api.K().G("autonav_notifications")&&p&&window.Notification&&typeof document.hasFocus==="function"){var C=Notification.permission;C==="default"?Notification.requestPermission():C!=="granted"||document.hasFocus()||(this.yD(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.b8()}),this.V=this.U(this.notification,"click",this.mZa),this.S.start())}this.QP();this.api.nextVideo(!1,p)};
g.h.m4=function(p){!g.iK(this.cancelButton.element,p.target)&&g.EO(p,this.api)&&(this.api.lW()&&this.api.logClick(this.rV("ytp-upnext-autoplay-icon")),this.select())};
g.h.uD=function(){this.api.lW()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.A_(this.api,!0)};
g.h.Acr=function(p){this.api.getPresentingPlayerType();this.show();this.pn(p)};
g.h.xZn=function(){this.api.getPresentingPlayerType();this.QP();this.hide()};
g.h.CS=function(){this.QP();this.yD();g.w.prototype.CS.call(this)};g.v(aU,hi);g.h=aU.prototype;g.h.create=function(){hi.prototype.create.call(this);this.S.U(this.player,"appresize",this.SP);this.S.U(this.player,"onVideoAreaChange",this.SP);this.S.U(this.player,"videodatachange",this.onVideoDataChange);this.S.U(this.player,"autonavchange",this.qv);this.S.U(this.player,"onAutonavCancelled",this.vT);this.onVideoDataChange()};
g.h.show=function(){hi.prototype.show.call(this);(this.D||this.V&&this.V!==this.videoData.clientPlaybackNonce)&&g.A_(this.player,!1);g.nT(this.player)&&this.RF()&&!this.V?(EP(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.T.select(!0):this.T.pn():this.videoData.autonavState===3&&this.T.qA()):(g.A_(this.player,!0),EP(this));this.SP()};
g.h.hide=function(){hi.prototype.hide.call(this);this.T.qA();EP(this)};
g.h.SP=function(){var p=this.player.v_(!0,this.player.isFullscreen());EP(this);iA(this.C);g.aL(this.element,"ytp-autonav-cancelled-small-mode",this.Qf(p));g.aL(this.element,"ytp-autonav-cancelled-tiny-mode",this.Bu(p));g.aL(this.element,"ytp-autonav-cancelled-mini-mode",p.width<=400||p.height<=360);this.overlay&&g.MK(this.overlay.element,{width:p.width+"px"});if(!this.W)for(p=0;p<this.videos.length;p++)g.aL(this.videos[p].element,"ytp-suggestion-card-with-margin",p%2===1)};
g.h.onVideoDataChange=function(){var p=this.player.getVideoData();if(this.videoData!==p&&p){this.videoData=p;if((p=this.videoData.suggestions)&&p.length||this.player.G("web_player_autonav_empty_suggestions_fix")){var C=g.B7(this.videoData);C&&(this.T.y_(C),this.T!==this.C&&this.C.y_(C))}if(p&&p.length)for(C=0;C<y81.length;++C){var V=y81[C];if(p&&p[V]){this.videos[C]=new Xb(this.player);var N=this.videos[C];V=p[V];N.suggestion!==V&&(N.suggestion=V,H9(N,V));g.R(this,this.videos[C]);this.videos[C].u_(this.J.element)}}this.SP()}};
g.h.qv=function(p){p===1?(this.D=!1,this.V=this.videoData.clientPlaybackNonce,this.T.QP(),this.n4&&this.SP()):(this.D=!0,this.lW()&&(p===2?this.T.pn():p===3&&this.T.qA()))};
g.h.vT=function(p){p?this.qv(1):(this.V=null,this.D=!1)};
g.h.RF=function(){return this.videoData.autonavState!==1};
g.h.Qf=function(p){return(p.width<910||p.height<459)&&!this.Bu(p)&&!(p.width<=400||p.height<=360)};
g.h.Bu=function(p){return p.width<800&&!(p.width<=400||p.height<=360)};
g.h.lW=function(){return this.n4&&g.nT(this.player)&&this.RF()&&!this.V};
var y81=[1,3,2,4];g.v(lA,g.w);g.h=lA.prototype;g.h.yB=function(){switch(this.buttonType){case 1:var p="Watch again on YouTube";var C=156915;break;case 2:p="Continue watching on YouTube";C=156942;break;default:p="Continue watching on YouTube",C=156942}this.update({content:p});this.N.hasVe(this.element)&&this.N.destroyVe(this.element);this.N.createClientVe(this.element,this,C)};
g.h.onClick=function(p){this.N.G("web_player_log_click_before_generating_ve_conversion_params")&&this.N.logClick(this.element);g.lT(this.getVideoUrl(),this.N,p);this.N.G("web_player_log_click_before_generating_ve_conversion_params")||this.N.logClick(this.element)};
g.h.getVideoUrl=function(){var p=!0;switch(this.buttonType){case 1:p=!0;break;case 2:p=!1}p=this.N.getVideoUrl(p,!1,!1,!0);var C=this.N.K();if(g.Mn(C)){var V={};g.Mn(C)&&g.TC(this.N,"addEmbedsConversionTrackingParams",[V]);p=g.LJ(p,V)}return p};
g.h.logVisibility=function(){this.N.logVisibility(this.element,this.n4&&this.Y)};
g.h.show=function(){g.w.prototype.show.call(this);this.logVisibility()};
g.h.hide=function(){g.w.prototype.hide.call(this);this.logVisibility()};
g.h.RH=function(p){g.w.prototype.RH.call(this,p);this.logVisibility()};g.v(ti,hi);ti.prototype.show=function(){this.player.getPlayerState()!==3&&(hi.prototype.show.call(this),this.T.iQ(!0),this.T.h2(!0),this.N.K().qt||this.T.Gf(!0),this.N.logVisibility(this.element,!0),this.watchButton.RH(!0))};
ti.prototype.hide=function(){hi.prototype.hide.call(this);this.T.iQ(!1);this.T.h2(!1);this.T.Gf(!1);this.N.logVisibility(this.element,!1);this.watchButton.RH(!1)};g.v(uup,hi);uup.prototype.Pr=function(){var p=this.player.getVideoData();this.T.update({profilePicture:p.profilePicture,author:p.author});this.subscribeButton.channelId=p.wb;var C=this.subscribeButton;p.subscribed?C.T():C.C()};g.v(c9,g.w);c9.prototype.select=function(){this.api.uy(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Ve||void 0)&&this.api.logClick(this.element)};
c9.prototype.onClick=function(p){if(g.Mn(this.api.K())&&this.api.G("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var C=this.suggestion.uT(),V={};g.xj(this.api,V);C=g.LJ(C,V);g.lT(C,this.api,p)}else g.EO(p,this.api,this.C,this.suggestion.sessionData||void 0)&&this.select()};
c9.prototype.onKeyPress=function(p){switch(p.keyCode){case 13:case 32:p.defaultPrevented||(this.select(),p.preventDefault())}};
c9.prototype.onVideoDataChange=function(){var p=this.api.getVideoData(),C=this.api.K();this.C=p.OV?!1:C.S};g.v(Ta,hi);g.h=Ta.prototype;g.h.create=function(){hi.prototype.create.call(this);var p=this.player.getVideoData();p&&(this.videoData=p);this.xE();this.C.U(this.player,"appresize",this.xE);this.C.U(this.player,"onVideoAreaChange",this.xE);this.C.U(this.player,"videodatachange",this.onVideoDataChange);this.C.U(this.player,"autonavchange",this.As);this.C.U(this.player,"onAutonavCancelled",this.z_);p=this.videoData.autonavState;p!==this.Z&&this.As(p);this.C.U(this.element,"transitionend",this.Dt$)};
g.h.destroy=function(){g.OB(this.C);g.s1(this.stills);this.stills=[];hi.prototype.destroy.call(this);g.hk(this.element,"ytp-show-tiles");this.D.stop();this.Z=this.videoData.autonavState};
g.h.RF=function(){return this.videoData.autonavState!==1};
g.h.show=function(){var p=this.n4;hi.prototype.show.call(this);g.hk(this.element,"ytp-show-tiles");this.player.K().C?g.Cg(this.D):this.D.start();(this.W||this.S&&this.S!==this.videoData.clientPlaybackNonce)&&g.A_(this.player,!1);M0(this)?(Ji(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.T.select(!0):this.T.pn():this.videoData.autonavState===3&&this.T.qA()):(g.A_(this.player,!0),Ji(this));p!==this.n4&&this.player.logVisibility(this.element,!0)};
g.h.hide=function(){var p=this.n4;hi.prototype.hide.call(this);this.T.qA();Ji(this);p!==this.n4&&this.player.logVisibility(this.element,!1)};
g.h.Dt$=function(p){p.target===this.element&&this.xE()};
g.h.xE=function(){var p,C,V,N;var H=((p=this.videoData)==null?0:(C=p.suggestions)==null?0:C.length)?(V=this.videoData)==null?void 0:V.suggestions:[(N=this.videoData)==null?void 0:g.B7(N)];if(H.length){g.d0(this.element,"ytp-endscreen-paginate");var X=this.N.v_(!0,this.N.isFullscreen());if(p=g.FE(this.N))p=p.Rd()?48:32,X.width-=p*2;var d=X.width/X.height;N=96/54;C=p=2;var a=Math.max(X.width/96,2),E=Math.max(X.height/54,2);V=H.length;var l=V*4;for(l-=4;l>0&&(p<a||C<E);){var t=p/2,c=C/2,T=p<=a-2&&l>=
c*4,M=C<=E-2&&l>=t*4;if((t+1)/c*N/d>d/(t/(c+1)*N)&&M)l-=t*4,C+=2;else if(T)l-=c*4,p+=2;else if(M)l-=t*4,C+=2;else break}N=!1;l>=12&&V*4-l<=6&&(C>=4||p>=4)&&(N=!0);l=p*96;a=C*54;d=l/a<d?X.height/a:X.width/l;d=Math.min(d,2);l=Math.floor(Math.min(X.width,l*d));a=Math.floor(Math.min(X.height,a*d));X=this.table.element;X.ariaLive="polite";g.UE(X,l,a);g.MK(X,{marginLeft:l/-2+"px",marginTop:a/-2+"px"});this.T.y_(g.B7(this.videoData));this.T instanceof dp&&iA(this.T);g.aL(this.element,"ytp-endscreen-takeover",
M0(this));Ji(this);l+=4;a+=4;d=0;X.ariaBusy="true";for(E=0;E<p;E++)for(t=0;t<C;t++)if(c=d,M=0,N&&E>=p-2&&t>=C-2?M=1:t%2===0&&E%2===0&&(t<2&&E<2?t===0&&E===0&&(M=2):M=2),c=g.E_(c+this.V,V),M!==0){T=this.stills[d];T||(T=new c9(this.player),this.stills[d]=T,X.appendChild(T.element));var J=Math.floor(a*t/C),S=Math.floor(l*E/p),D=Math.floor(a*(t+M)/C)-J-4,Z=Math.floor(l*(E+M)/p)-S-4;g.K2(T.element,S,J);g.UE(T.element,Z,D);g.MK(T.element,"transitionDelay",(t+E)/20+"s");g.aL(T.element,"ytp-videowall-still-mini",
M===1);g.aL(T.element,"ytp-videowall-still-large",M>2);M=Math.max(Z,D);g.aL(T.element,"ytp-videowall-still-round-large",M>=256);g.aL(T.element,"ytp-videowall-still-round-medium",M>96&&M<256);g.aL(T.element,"ytp-videowall-still-round-small",M<=96);c=H[c];T.suggestion!==c&&(T.suggestion=c,M=T.api.K(),J=g.XV(T.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",H9(T,c,J),g.Mn(M)&&!T.api.G("web_player_log_click_before_generating_ve_conversion_params")&&(M=c.uT(),J={},g.TC(T.api,"addEmbedsConversionTrackingParams",
[J]),M=g.LJ(M,J),T.updateValue("url",M)),(c=(c=c.sessionData)&&c.itct)&&T.api.setTrackingParams(T.element,c));d++}X.ariaBusy="false";g.aL(this.element,"ytp-endscreen-paginate",d<V);for(H=this.stills.length-1;H>=d;H--)p=this.stills[H],g.dW(p.element),g.hf(p);this.stills.length=d}};
g.h.onVideoDataChange=function(){var p=this.player.getVideoData(1);this.videoData!==p&&(p!=null&&g.B7(p)?(this.V=0,this.videoData=p,this.xE()):this.player.k_("missg",{vid:(p==null?void 0:p.videoId)||"",cpn:(p==null?void 0:p.clientPlaybackNonce)||""}))};
g.h.iD=function(){this.V+=this.stills.length;this.xE()};
g.h.fb=function(){this.V-=this.stills.length;this.xE()};
g.h.nL=function(){return this.T.WI()};
g.h.As=function(p){p===1?(this.W=!1,this.S=this.videoData.clientPlaybackNonce,this.T.QP(),this.n4&&this.xE()):(this.W=!0,this.n4&&M0(this)&&(p===2?this.T.pn():p===3&&this.T.qA()))};
g.h.z_=function(p){if(p){for(p=0;p<this.stills.length;p++)this.N.logVisibility(this.stills[p].element,!0);this.As(1)}else this.S=null,this.W=!1;this.xE()};
g.h.lW=function(){return this.n4&&M0(this)};g.v(m7,hi);m7.prototype.hasSuggestions=function(){var p;return(p=this.T)==null?void 0:p.hasSuggestions()};
m7.prototype.show=function(){if(this.player.getPlayerState()!==3){hi.prototype.show.call(this);var p=this.C;if(p){var C=this.T.hasSuggestions();g.aL(this.element,"ytp-shorts-branded-ui",C);C?p.show():p.hide()}var V;(V=g.FE(this.player))==null||V.fn(!0);this.player.logVisibility(this.element,!0);this.watchButton.RH(!0)}};
m7.prototype.hide=function(){hi.prototype.hide.call(this);var p;(p=g.FE(this.player))==null||p.fn(!1);this.player.logVisibility(this.element,!1);this.watchButton.RH(!1)};g.v(OJ2,g.IT);g.h=OJ2.prototype;g.h.Ot=function(){var p=this.player.getVideoData(),C=p.G("embeds_enable_full_length_inline_muted_autoplay")?p.mutedAutoplay&&(p.limitedPlaybackDurationInSeconds>0||p.endSeconds>0):p.mutedAutoplay;if((this.player.isEmbedsShortsMode()||this.C)&&!C)return!0;var V;var N=!!((p==null?0:g.B7(p))||(p==null?0:(V=p.suggestions)==null?0:V.length));N=!ZJc(this.player)||N;p=p.Uf;V=this.player.Ho();return N&&!p&&!V&&!C};
g.h.lW=function(){return this.endScreen.lW()};
g.h.rkn=function(){return this.lW()?this.endScreen.nL():!1};
g.h.CS=function(){this.player.p7("endscreen");g.IT.prototype.CS.call(this)};
g.h.load=function(){var p=this.player.getVideoData();var C=p.transitionEndpointAtEndOfStream;if(C&&C.videoId){var V=this.player.Tk().Ji.get("heartbeat"),N=g.B7(p);!N||C.videoId!==N.videoId||p.RK?(this.player.uy(C.videoId,void 0,void 0,!0,!0,C),V&&V.Xl("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),p=!0):p=!1}else p=!1;p||(g.IT.prototype.load.call(this),this.endScreen.show())};
g.h.unload=function(){g.IT.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.h.onCueRangeEnter=function(p){this.Ot()&&(this.endScreen.created||this.endScreen.create(),p.getId()==="load"&&this.load())};
g.h.onCueRangeExit=function(p){p.getId()==="load"&&this.loaded&&this.unload()};
g.h.onVideoDataChange=function(){fC1(this);this.S&&U7r(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.T?this.endScreen=new aU(this.player):this.endScreen=new Ta(this.player),g.R(this,this.endScreen),g.R$(this.player,this.endScreen.element,4))};g.qA("endscreen",OJ2);})(_yt_player);
